Restore descriptions and display
maykinmedia/commonground-api-common pull request #17
Opened 2023-12-01 16:59 UTC by Coperh

Fixes: https://github.com/open-zaak/open-zaak/issues/1490

2023-12-07 16:02 UTC, annashamray requested changes
It looks quite neat, I like the approach

2023-12-11 10:09 UTC, Coperh commented on vng_api_common/choices.py
> +    def get_descriptions(cls):
Done

2023-12-11 10:09 UTC, Coperh commented on vng_api_common/apps.py
> +    for cls in TextChoicesWithDescriptions.__subclasses__():
Made it recursive, so it should run on subclasses.

2023-12-11 10:09 UTC, Coperh commented on vng_api_common/choices.py
> +def ensure_description_exists(cls):
Done

2023-12-19 16:57 UTC, annashamray approved these changes

2023-12-20 14:41 UTC, merged