Improving the validation rsin and bsn
maykinmedia/commonground-api-common pull request #58
Opened 2024-12-30 13:43 UTC by danielmursa-dev

Create a BaseValidator that include 
```
- validate_isdigit
- validate_length
- validate_11proefnumber
```

2025-01-02 13:36 UTC, stevenbal requested changes

2025-01-02 13:36 UTC, stevenbal commented on vng_api_common/validators.py
> +                self.error_messages["11proefnumber"], code="invalid-code"
Let's keep this the same for backward compatibility
```suggestion
                self.error_messages["11proefnumber"], code="invalid"
```

2025-01-02 13:36 UTC, stevenbal commented on vng_api_common/validators.py
> +class BaseValidator:
Not 100% sure what to call this, but maybe something like this is slightly clearer
```suggestion
class BaseIdentificationValidator:
```

2025-01-02 13:36 UTC, stevenbal commented on vng_api_common/validators.py
> +def validate_rsin(value):
```suggestion
def validate_rsin(value: str):
```

2025-01-02 13:36 UTC, stevenbal commented on vng_api_common/validators.py
> +def validate_bsn(value):
```suggestion
def validate_bsn(value: str):
```

2025-01-02 13:36 UTC, stevenbal commented on vng_api_common/constants.py
> +BSN_LIST_SIZE = [8, 9]
@sergei-maertens do you know if 8 numbers is also allowed for these? I seem to find conflicting information when looking this up
- https://www.rijksoverheid.nl/onderwerpen/privacy-en-persoonsgegevens/vraag-en-antwoord/wat-is-het-burgerservicenummer-bsn mentions 9 for BSN
- https://www.nederlandwereldwijd.nl/bsn/wat-is-bsn mentions 8 or 9 for BSN

For RSIN I only see 9 mentioned

2025-01-02 14:21 UTC, sergei-maertens commented on vng_api_common/constants.py
> +BSN_LIST_SIZE = [8, 9]
I think historically SOFI number could be 8 digits, but as far as I understand this is phased out entirely and only 9 digit numbers are allowed. I haven't gotten any error reports yet from places that don't support 8 chars, so I'd just try sticking to 9. But, maybe @alextreme has more insights with his experience from BD?

2025-01-02 14:27 UTC, alextreme commented on vng_api_common/constants.py
> +BSN_LIST_SIZE = [8, 9]
Naturally: in the same category as EBDIC and CSV files, voorloopnullen for 8-digit BSN's are the bane of BD. e.g. 011122233 != 11122233

I'd want to avoid 8-digit BSNs as much as possible, but if this is what I think it is then it may be too late...

2025-01-13 08:45 UTC, stevenbal requested changes

2025-01-13 08:45 UTC, stevenbal commented on vng_api_common/constants.py
> +BSN_LIST_SIZE = [8, 9]
These two should be changed to only support 9 digits

2025-01-13 09:25 UTC, merged